### PR TITLE
Fixed JSON response example in Tournament Search

### LINKED ISSUE #47: Tournaments endpoint not returning type
_From @ZeNeLLiE on July 26, 2018 2:19_

https://api.royaleapi.com/tournaments/search?name=b

type is not returned. ("open", "passwordProtected")

Expected:

> [
>     {
>         "tag": "20CVYRV8",
>         "type": "open",
>         "status": "inPreparation",
>         "creatorTag": "#99Y90URP8",
>         "name": "Andrei Geanta",
>         "maxCapacity": 50,
>         "preparationDuration": 7200,
>         "duration": 3600,
>         "createTime": 1520249970,
>         "startTime": null,
>         "endTime": null,
>         "playerCount": 50,
>         "members": []
>     },
>     {
>         "tag": "C9LRLP0",
>         "type": "passwordProtected",
>         "status": "inProgress",
>         "creatorTag": "#989G8QLCG",
>         "name": "ali",
>         "description": "vous pouvez pas rejoindre",
>         "maxCapacity": 100,
>         "preparationDuration": 7200,
>         "duration": 3600,
>         "createTime": 1520251673,
>         "startTime": null,
>         "endTime": null,
>         "playerCount": 29,
>         "members": []
>     },
> ]

Actual:

>  {
>         "tag": "29CV0PQG",
>         "name": "bora jogar",
>         "open": true,
>         "maxPlayers": 50,
>         "currentPlayers": 50,
>         "status": "inProgress",
>         "createTime": 1532564781,
>         "prepTime": 7200,
>         "startTime": null,
>         "endTime": null,
>         "duration": 3600,
>         "description": "entra quem quiser",
>         "updatedAt": 1532571124,
>         "members": []
>     },

_Copied from original issue: RoyaleAPI/cr-api#413_

### PR DESCRIPTION
**Pull request by jegfish**
resolves #47

### CODE REVIEW

**Review by fourjr — CHANGES_REQUESTED** [review]
This isn't the only breaking change recently, refer below:

**Comment by jegfish** [comment]
:sweat_smile: I can't believe I forgot to make the changes I mentioned myself.
Just committed them, everything should be good to go.

**Review by fourjr — CHANGES_REQUESTED** [review]
other endpoints like 1k, open, /tournament might also need updating :(

**Comment by jegfish** [comment]
I have all the tournament endpoints finished, would appreciate a double check.

There was a special case for Popular Tournaments. The data is not wrong, it is incomplete. *However* this appears to be intended to not take up too much space.
```json
[
    {
        "popularity": {
            "hits": "35",
            "hitsPerDayAvg": 11.67
        },
        "tag": "...",
    },
    {}
]
```
The same lack of data is used in the other Popular endpoints. Might be good to complete this data, but it's not really relevant to this PR.

**Review by fourjr — APPROVED** [review]

**Comment by fourjr** [comment]
thank you!

**Pull request merged**
